### ISSUE TITLE
Preferred Release Type

### ISSUE THREAD

**Issue by nikita488** [DaemonicLabs/Voodoo#14]
Is there is any way to tell Voodoo to download "Preferred Release Type" of mods? I mean if i want to have Release versions of mods, but some mods still in Beta or Alpha and Voodoo seems like throw error if it can't find specified type. For example Twitch Launcher have "Preferred Release Type" option and it will download exactly specified release type, but if mod don't have that release type, it will download Beta or Alpha. Same thing applies to mod dependencies. I mean it seems like i can actually use "curseReleaseTypes: [...]" to specify release type for every mod, but this will require to check every mod on Curse and it will be a problem if i have a modpack with a lot of mods.

**Comment by NikkyAI** [comment]
you set the allowed release types in the root entry usually, i would gi with Alpha, beta and Release
and then narrow it down for single entries

i am sorry but i do not want to add any options that are not very clear, if a mod does not have a release and you only search for release it is supposed to error

and again the yaml format is nested.. options in the root entry are applied to all child entries unless those have them overridden

```yaml
root:
  provider: "CURSE"
  validMcVersions:
  - "1.12.1"
  - "1.12"
  curseReleaseTypes:
  - RELEASE
  - BETA
  - ALPHA
  entries:
  - baubles
  - bookshelf
  - ...
  - curseReleaseTypes:
    - RELEASE
   entries:
   - rf-tools

```

maybe this sample helps you out.. otherwise feel free to join any of the linked chats (in the README) and i can provide better support
