### ISSUE TITLE
provider: SOURCE

### ISSUE THREAD

**Issue by NikkyAI** [DaemonicLabs/Voodoo#2]
compile mods from source

example
```yaml
provider: SOURCE
git: https://github.com/elytra/MatterLink.git
commit/branch: master # or commit hash / tag
command: gradlew setupCiWorkspace clean build
archive: 'build/libs/*.jar'
```

will clone the repo, run the command and then copy the result, basically like jenkins

figure out a way to make sure to only grab the mod and not the sources, api or other unwanted binaries
maybe error when there is multiple files matching the regex

requires: git library and calling gradlew
